# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-07 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebContent', '0003_auto_20170527_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='WebContent.ContentTag'),
        ),
    ]
