# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-09 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebContent', '0005_auto_20200407_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttag',
            name='context',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
