# Generated by Django 5.1.7 on 2025-03-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebContent', '0007_update_foreign_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Allow anonymous users to view this content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contenttag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
