# Generated by Django 5.1.7 on 2025-03-20 17:09

from django.db import migrations
from django.contrib.auth.models import User, Group
from django.utils import timezone
from django.core.files.base import ContentFile
from WebContent.models import Content, Page, FileUpload, ContentTag

def create_demo_content(apps, schema_editor):
    # Create or get superuser
    user, created = User.objects.get_or_create(
        username='admin',
        defaults={
            'email': 'admin@example.com',
            'is_staff': True,
            'is_superuser': True
        }
    )
    if created:
        user.set_password('admin')
        user.save()

    # Create admin group
    admin_group, created = Group.objects.get_or_create(name='admin')
    if created:
        user.groups.add(admin_group)

    # Create tags
    tags = {
        'news': ContentTag.objects.create(name='news'),
        'documentation': ContentTag.objects.create(name='documentation'),
        'tutorial': ContentTag.objects.create(name='tutorial'),
    }

    # Create pages
    pages = {
        'welcome': Page.objects.create(
            slug='welcome',
            html='''
                <h1>Welcome to Django WebContent</h1>
                <p>This is a demo page showing the capabilities of the WebContent app.</p>
                <h2>Features</h2>
                <ul>
                    <li>Create and manage web pages</li>
                    <li>Upload and share files</li>
                    <li>Organize content with tags</li>
                    <li>Control access with user permissions</li>
                </ul>
            ''',
            owner=user,
            pub_date=timezone.now()
        ),
        'getting-started': Page.objects.create(
            slug='getting-started',
            html='''
                <h1>Getting Started</h1>
                <p>Follow these steps to get started with Django WebContent:</p>
                <ol>
                    <li>Install the package using pip</li>
                    <li>Add "WebContent" to INSTALLED_APPS</li>
                    <li>Run migrations</li>
                    <li>Create your first content</li>
                </ol>
            ''',
            owner=user,
            pub_date=timezone.now()
        ),
    }

    # Create a demo file
    demo_file_content = b'This is a demo file content.\nIt shows how to upload and manage files in WebContent.'
    demo_file = ContentFile(demo_file_content, name='demo.txt')
    file_upload = FileUpload.objects.create(
        slug='demo-file',
        fileContent=demo_file,
        owner=user,
        pub_date=timezone.now()
    )

    # Add tags to content
    pages['welcome'].tags.add(tags['news'])
    pages['getting-started'].tags.add(tags['documentation'], tags['tutorial'])
    file_upload.tags.add(tags['documentation'])

    # Add admin group to all content
    for content in [pages['welcome'], pages['getting-started'], file_upload]:
        content.authGroup.add(admin_group)

def remove_demo_content(apps, schema_editor):
    # Remove all demo content
    Content.objects.filter(slug__in=['welcome', 'getting-started', 'demo-file']).delete()
    ContentTag.objects.filter(name__in=['news', 'documentation', 'tutorial']).delete()
    Group.objects.filter(name='admin').delete()
    User.objects.filter(username='admin').delete()

class Migration(migrations.Migration):
    dependencies = [
        ('WebContent', '0007_update_foreign_keys'),
    ]

    operations = [
        migrations.RunPython(create_demo_content, remove_demo_content),
    ]
